/** @type {import('tailwindcss').Config} */
export default {
	content: [
		'./components/**/*.{js,vue,ts}',
		'./layouts/**/*.vue',
		'./pages/**/*.vue',
		'./plugins/**/*.{js,ts}',
		'./nuxt.config.{js,ts}',
		'./app.vue',
	],
	theme: {
		extend: {
			colors: {
				primary: 'rgba(var(--color-primary))',
				secondary: 'rgba(var(--color-secondary))',
				tertiary: 'rgba(var(--color-tertiary))',
				quad: 'rgba(var(--color-quaternary))',
				pentary: 'rgba(var(--color-penta))',
				overlay: 'rgba(var(--color-overlay))',
				overlay1: 'rgba(var(--color-overlay1))',
				foreground: 'rgba(var(--color-fore))',
				background: 'rgba(var(--color-back))',
				maintext: 'rgba(var(--color-text))',
				hero: 'rgba(var(--color-hero))',
				altbackground: 'rgba(var(--color-fore))',
			},
			fontFamily: {
				adam: ['adam', 'sans-serif'],
				adam_med: ['adam-med', 'sans-serif'],
				geosans: ['geosans', 'sans-serif'],
				garet: ['garet', 'sans-serif'],
				comforta: ['comforta', 'sans-serif'],
				caviar: ['caviar', 'sans-serif'],
				holen: ['holen', 'sans-serif'],
				avigea: ['avigea', 'sans-serif'],
				wonderland: ['wonderland', 'sans-serif'],
				heavitas: ['heavitas', 'trebuchet ms'],
				akira: ['akira', 'trebuchet ms'],
				robotobold: ['robotobold', 'trebuchet ms'],
				roboto: ['roboto', 'trebuchet ms'],
				junegull: ['junegull', 'trebuchet ms'],
				agresive: ['agresive', 'trebuchet ms'],
				sans: ['Graphik', 'sans-serif'],
				serif: ['Merriweather', 'serif'],
			},
		},
	},
	plugins: [],
}
